spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/smartwallet
spring.datasource.username=postgres
spring.datasource.password=04072004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8003


jwt.secret=0582004N04072004367639792F423A4528482B4D6251655468576D5A71347437
jwt.expiration=604800000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mejdoubabir272@gmail.com
spring.mail.password=rxnt elmg aspb ifhp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
gemini.api.key=AIzaSyC1rjaPVgvVTxW7EbgiW7U4NvPoyySTYVE
app.server.url=http:// 192.168.100.6:8003
app.frontend.url=http:// 192.168.100.6:4200
